apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestkit-workers

resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- daemonset.yaml

commonLabels:
  app: guestkit
  managed-by: kustomize
